### PR TITLE
Restore using the mysql binary to prevent memory errors.

### LINKED ISSUE #18: Getting Allowed memory
Hello,

I have a big DB, when I try the sync I get error something like: `Allowed memory size of 536870912 bytes exhausted (tried to allocate 477174084 bytes)`

### PR DESCRIPTION
**Pull request by m-popa**
Modify the restore process, so that it uses mysql instead to prevent memory issues.

This should close #18 and simplify the restore process, along with increasing the speed of the restore.

### CODE REVIEW

**Comment by niladam** [comment]
hey @dcblogdev -- i know you must be pretty busy but could you maybe have a look at this ?:)

**Comment by dcblogdev** [comment]
I'm away with work at the moment, I'll be able to look at this next week, thanks for raising it

**Comment by niladam** [comment]
Hey @dcblogdev i was wondering why this is still open. Is there an issue with it? Is there something wrong with it?

I'm not trying to be pushy, just trying to understand why this hasn't been merged as it's been a while since it has been created..

**Comment by dcblogdev** [comment]
my apologies, I will get to this today.

**Pull request merged**
